- name: Copy unit files
  template:
    src: "{{ item }}"
    dest: /etc/containers/systemd/{{ item | basename | replace('.j2', '',) | replace('rkb', rkb_name) }}
  loop:
    - units/rkb.container.j2
    - units/rkb.image.j2
  notify: reload systemd
  tags:
    - rkb

- import_tasks: validate.yml
