- name: Stop services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - "{{ rkb_name }}-image"
    - "{{ rkb_name }}"
  ignore_errors: yes

- name: Remove container image
  ansible.builtin.command:
    cmd: podman rmi {{ rkb_container_image }}
  register: _rkb_rmi
  changed_when: _rkb_rmi.rc == 0
  failed_when: false

- name: Remove unit files
  file:
    path: /etc/containers/systemd/{{ item }}
    state: absent
  loop:
    - "{{ rkb_name }}.image"
    - "{{ rkb_name }}.container"
  notify: reload systemd
