- name: Setup Lightspeed Stack
  kubernetes.core.k8s:
    state: "{{ ls_state }}"
    template: templates/k8s/{{ item }}
  loop:
    - ls-configmap.j2
    - ls-deployment.j2
    - ls-route.j2
    - ls-service.j2
    - ls-serviceaccount.j2
  tags:
    - ls
