- name: Create config directory
  file:
    path: /var/lib/containers/lightspeed-stack
    state: directory
    mode: '0755'
    owner: root
    group: root
  tags:
    - ls

- name: Copy config files
  template:
    src: "{{ item }}"
    dest: /var/lib/containers/lightspeed-stack/{{ item }}
  loop:
    - lightspeed-stack.yml
    - system_prompt.txt
  notify: init
  tags:
    - ls

- name: Copy unit files
  template:
    src: "{{ item }}"
    dest: /etc/containers/systemd/{{ item | basename | replace ('.j2', '' ) | replace('ls', ls_name) }}
  loop:
    - units/lightspeed-stack.image.j2
    - units/lightspeed-stack.container.j2
  notify: init
  tags:
    - ls
