apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rhel-lightspeed/rhel-cla-installer?rev={{ revision }}
    build.appstudio.redhat.com/commit_sha: '{{ revision }}'
    build.appstudio.redhat.com/target_branch: '{{ target_branch }}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "push"
      && (
        target_branch == "main"
        || target_branch.startsWith("release/")
        || target_branch.startsWith("refs/tags/")
      )

  creationTimestamp: null

  labels:
    appstudio.openshift.io/application: rhel-cla-installer
    appstudio.openshift.io/component: rhel-cla-installer
    pipelines.appstudio.openshift.io/type: build

  namespace: rhel-lightspeed-tenant
  name: rhel-cla-installer-on-push

spec:
  params:
    - name: output-image
      value: quay.io/redhat-user-workloads/rhel-lightspeed-tenant/rhel-cla-installer:{{ revision }}

    - name: additional-tags
      value:
        - latest

    # Tell konflux to read the tag from Containerfile label.
    - name: additional-tags-from-label
      value:
        - konflux.additional-tags

  pipelineRef:
    name: pipeline-build-multiarch

  taskRunTemplate:
    serviceAccountName: build-pipeline-rhel-cla-installer

  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
