- name: Setup Red Hat Offline Knowledge Portal
  kubernetes.core.k8s:
    state: "{{ okp_state }}"
    template: templates/k8s/{{ item }}
  loop:
    - okp-configmap.j2
    - okp-deployment.j2
    - okp-service-account.j2
    - okp-service.j2

