- name: Install
  when: okp_state != "absent"
  block:
    - name: Create image
      template:
        src: units/okp.image.j2
        dest: /etc/containers/systemd/{{ okp_name }}.image
      notify: reload systemd

    - name: Create container
      template:
        src: units/okp.container.j2
        dest: /etc/containers/systemd/{{ okp_name }}.container
      notify: reload systemd

- name: Remove
  include_tasks: remove.yml
  when: okp_state == "absent"
