- name: Copy unit files
  template:
    src: "{{ item }}"
    dest: /etc/containers/systemd/{{ item | basename | replace ('.j2', '' ) | replace('okp', okp_name) }}
  loop:
    - units/okp.container.j2
    - units/okp.image.j2
  notify: init
  tags:
    - okp
