- name: Stop services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - "{{ okp_name }}-image"
    - "{{ okp_name }}"
  ignore_errors: yes
  tags:
  - okp

- name: Remove unit files
  file:
    path: /etc/containers/systemd/{{ item }}
    state: absent
  loop:
    - "{{ okp_name }}.container"
    - "{{ okp_name }}.image"
  notify: cleanup
  tags:
  - okp
