- name: Setup RHEL CLA
  hosts: okp
  become: yes

  handlers:
    - name: Restart RHEL CLA pod
      systemd:
        name: "{{ cla_pod_name }}-pod"
        state: restarted
        daemon_reload: yes
      listen:
        - init

  tasks:
    - import_role:
        name: cla_pod

    - import_role:
        name: okp

    - import_role:
        name: rhel_knowledge_bridge

    - import_role:
        name: lightspeed_stack
