- name: Setup RHEL CLA in K8S
  hosts: localhost
  gather_facts: no
  become: no

  tasks:
    - import_role:
        name: okp
        tasks_from: k8s

    - import_role:
        name: rhel_knowledge_bridge
        tasks_from: k8s

    - import_role:
        name: lightspeed_stack
        tasks_from: k8s
