- name: Setup RHEL CLA locally
  hosts: localhost
  become: yes
  gather_facts: no

  vars:
    okp_solr_port: 8983
    okp_pod_name: rhel-cla

  tasks:
    - import_role:
        name: rhel_knowledge_bridge

    - import_role:
        name: okp
