- name: Remove RHEL CLA
  hosts: all
  become: yes

  vars:
    okp_solr_port: 8983
    state: absent
    cla_state: "{{ state }}"
    okp_state: "{{ state }}"
    ls_state: "{{ state }}"
    rkb_state: "{{ state }}"

  tasks:
    - import_role:
        name: cla_pod

    - import_role:
        name: rhel_knowledge_bridge

    - import_role:
        name: okp
