- name: Create pod
  template:
    src: "{{ cla_pod_name }}.pod.j2"
    dest: /etc/containers/systemd/{{ cla_pod_name }}.pod
  notify: init
  tags:
    - cla_pod

- name: Start the pod
  systemd:
    name: "{{ cla_pod_name }}-pod"
    state: started
    daemon_reload: yes
  tags:
    - always
